#! /bin/sh
# File              : bspwmrc
# Author            : Anton Riedel <anton.riedel@tum.de>
# Date              : 08.04.2020
# Last Modified Date: 10.04.2020
# Last Modified By  : Anton Riedel <anton.riedel@tum.de>

#startup programs are launched in $HOME/.xinitrc like sxhkd and ploybar

#monitor setup
bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

#window settings
bspc config border_width                  3
bspc config window_gap                    8
bspc config top_padding                   24 #height of polybar
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

#split ratio for tiled layout
bspc config split_ratio                   0.50

#no borders or gaps in monocle layout
bspc config borderless_monocle            true
bspc config gapless_monocle               true

#use monocle layout if there is only one window
bspc config single_monocle                true

#switch focus to the window the mouse is pointing to
bspc config focus_follows_pointer         true

#change the default X shaped cursor to a pointer
xsetroot -cursor_name left_ptr

#move and resize floating windows with the mouse and super
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#colors
bspc config normal_border_color     "4c566a"
bspc config active_border_color     "#1e1e1e"
bspc config focused_border_color    "#406ea5"
bspc config presel_feedback_color   "#5e81ac"
bspc config urgent_border_color     "#dd2727"
