# File              : prod.yml
# Author            : Anton Riedel <anton.riedel@tum.de>
# Date              : 12.10.2021
# Last Modified Date: 17.02.2022
# Last Modified By  : Anton Riedel <anton.riedel@tum.de>
session_name: Productivity
windows:
  - window_name: Focus
    focus: true
    panes:
      - shell_command: echo "Start to focus"
  - window_name: Mail
    panes:
      - shell_command: neomutt
  - window_name: DenseAndStrange
    panes:
      - shell_command: slack-term -config $HOME/.config/slack-term/DenseAndStrange
  - window_name: FemtoBoyz
    panes:
      - shell_command: slack-term -config $HOME/.config/slack-term/FemtoBoyz
  - window_name: Mupa
    panes:
      - shell_command: slack-term -config $HOME/.config/slack-term/Mupa
