#! /bin/sh
# File              : bspwmrc
# Author            : Anton Riedel <anton.riedel@tum.de>
# Date              : 08.04.2020
# Last Modified Date: 09.04.2020
# Last Modified By  : Anton Riedel <anton.riedel@tum.de>

#startup programs are launched in $HOME/.xinitrc like sxhkd and ploybar

#Monitor
bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9

#Global Settings
#bspc config automatic_scheme alternate
#bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 28
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 5

###---Rules---###
bspc config border_width 3
bspc config window_gap 8
