#!/bin/sh
# File              : aliasrc
# Author            : Anton Riedel <anton.riedel@tum.de>
# Date              : 24.03.2020
# Last Modified Date: 02.06.2021
# Last Modified By  : Anton Riedel <anton.riedel@tum.de>

##aliases
alias ls='ls --color=auto'
alias ll='ls -alh --color=auto'
alias grep='grep --color=auto'
alias scp='rsync -uvrzP'
#alias scp='rsync -uvrzP --zc=zlib'
alias pdf='$READER'
alias pdf2='$READER2'
alias latexmk='latexmk -pdf'
alias v='$EDITOR'
alias vi='$EDITOR'
alias vim='$EDITOR'
alias vb='$EDITOR -u NONE'
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gch='git checkout'
alias gb='git branch'
if grep -q "Arch Linux" /etc/os-release; then
	alias pi='paru -S'
	alias pu='paru -Syu'
	alias pr='paru -Rnsc'
	alias po='paru -Qtdq | paru -Rns -'
	alias pc='paru Scc'
	alias pq='paru -Ss'
	# alias pi='sudo pacman -S'
	# alias pu='sudo pacman -Syu'
	# alias pr='sudo pacman -rnsc'
	# alias po='sudo pacman -qtdq | sudo pacman -rns -'
	# alias pc='pacman Scc'
	# alias pq='pacman -Ss'
elif grep -q "Debian\|ubuntu" /etc/os-release; then
	alias pu='sudo apt update && sudo apt upgrade && sudo apt autoremove'
	alias pi='sudo apt install'
	alias pr='sudo apt purge'
	alias pq='apt search'
fi
alias nmu='nmcli con up --ask'
alias nmd='nmcli con down'
alias screen='xinput --map-to-output "wacom isdv4 e6 pen pen (0)" lvds1 --map-to-output "wacom isdv4 e6 pen eraser (0)" lvds1'

##custom shell functions (a.k.a. fun with fzf)
#search and edit a configuration file
ce() {
	$EDITOR "$(find $HOME/Dotfiles -type f -not -path "*/old/*" | fzf --prompt="Edit config file: ")"
	return 0
}
#connect to known host via ssh
sshc() {
	# choose a host from all known hosts
	Host="$(grep -r "^Host " $HOME/.ssh/config.d | grep -v "git\|\*" | awk '{print $2}' | fzf --prompt="Connect to host: ")"

	if grep -q "sun" <<<"$Host"; then
		#key with passphrase; hence we need sshpass -P
		export SSHPASS="$(pass sun/key)"
		sshpass -P "passphrase" -e ssh "$Host"
	elif grep -q "cipgate\|jump\|t30" <<<"$Host"; then
		#need password for cipgate and t30gate
		export SSHPASS="$(pass email/tum)"
		sshpass -e ssh "$Host"
	else
		#all others normally do not need a password
		ssh "$Host"
	fi
	export SSHPASS=""

	return 0
}
#search and enter a subdirectory in your home directory
fd() {
	cd "$(find $HOME -type d -not -path "*/old/*" | fzf --prompt="Jump to Dir: ")"
	pwd
	ls
	return 0
}
#search and open a file in your home directory
ff() {
	xdg-open "$(find $HOME -type f -not -path "*/old/*" | fzf --prompt="Open file: ")"
	return 0
}
#search for a process and kill it
kp() {
	kill -s SIGKILL "$(ps aux | fzf --prompt="Job to kill: " | awk '{ print $2 }')" 2>/dev/null
	return 0
}
#copy a content of file in the current directory to clipboard
ctc() {
	File="$(find . -maxdepth 1 -type f | fzf --prompt="Copy file to clipboard: ")"
	xclip -selection clipboard $File
	return 0
}
