---
- name: Create XDG direcotries
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ XDG }}"

- include_tasks: archlinux_config.yml
  when: ansible_os_family == "Archlinux"

- include_tasks: debian_config.yml
  when: ansible_os_family == "Debian"
