#! /bin/bash
#################################################################################
#     File Name           :     battery
#     Created By          :     Anton Riedel <anton.riedel@hotmail.com>
#     Creation Date       :     [2019-02-24 11:38]
#     Last Modified       :     [AUTO_UPDATE_BEFORE_SAVE]
#     Description         :     Script for i3blocks (display state of the
#                               Battery)
#################################################################################

case $BLOCK_BUTTON in
    1) pgrep -x dunst >/dev/null && notify-send "<b>🔋 Battery module:</b>
⛽: no battery
🔋: discharging
♻: stagnant charge
🔌: charging
⚡: charged" ;;
esac

if [ "$(hostname)" == "Mars" ]; then
    BAT="BAT0"
else
    BAT="BAT1"
fi

if [ -d /sys/class/power_supply/$BAT ]; then
    capacity=$(cat /sys/class/power_supply/$BAT/capacity)
    status=$(cat /sys/class/power_supply/$BAT/status)
    wear=$(bc <<< "scale=2; $(cat /sys/class/power_supply/$BAT/charge_full) / $(cat /sys/class/power_supply/$BAT/charge_full_design)")
else
    echo "⛽" || exit
fi

echo $(echo "$status" | sed -e "s/,//g;s/Discharging/🔋/;s/Charging/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g") $(echo "$capacity" | sed -e 's/$/%/') $(echo \($wear\))
