#! /bin/bash
#################################################################################
#     File Name           :     cpu
#     Created By          :     Anton Riedel <anton.riedel@hotmail.com>
#     Creation Date       :     [2019-02-24 11:39]
#     Last Modified       :     [AUTO_UPDATE_BEFORE_SAVE]
#     Description         :     Script for i3blocks (display CPU usage and
#                               temperature)
#################################################################################

case $BLOCK_BUTTON in
	1) notify-send "<b>🖥 CPU hogs</b>:
$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
	3) notify-send "<b>🖥 CPU module:</b>
- Shows CPU temperature.
- Click to show intensive processes.
- % is of single core." ;;
esac

sensors | awk '/Core 0/ {print $3}'
